name: Secretos
run-name: Aprendiendo sobre secretos
on: 
  workflow_dispatch: 
    inputs:
      saludo:
        description: 'Tu saludo'
        default: 'Hola'
        required: true
        type: string


env: 
    REPO_NAME: ${{ github.repository }}
    BRANCH: ${{ github.ref }}

jobs:
    workflow-vars:
        runs-on: ubuntu-latest 
        env: 
            JOB_ID: 0 
            WORKFLOW_NAME: ${{ github.workflow }}
        steps:
            - name: Repo info 
              run: echo "Repository name  ${{ env.REPO_NAME }} in branch ${{ env.BRANCH }}" 
            - name: workflow info 
              run: echo "Running job ${{ env.JOB_ID }} of ${{ env.WORKFLOW_NAME }} in step ${{ env.STEP_NAME }}"
              env: 
                STEP_NAME: workflowInfo
    saludo-secretos:
        runs-on: ubuntu-latest 
        steps: 
          - name: saludos scretos
            run: echo "${{ inputs.saludo }} ${{ vars.NOMBRE }},El secreto PSWD para ${{ env.REPO_NAME}} es ${{ secrets.REPO_PSWD}}"


    

