name: Varibles
run-name: Aprendiendo sobre variables
on: [ push ]
env: 
    REPO_NAME: ${{ github.repository }}
    BRANCH: ${{ github.ref }}

jobs:
    workflow-vars:
        runs-on: ubuntu-latest 
        env: 
            JOB_ID: 0 
            WORKFLOW_NAME: ${{ github.workflow }}
        steps:
            - name: Repo info 
              run: echo "Repository name  ${{ env.REPO_NAME }} in branch ${{ env.BRANCH }}" 
            - name: workflow info 
              run: echo "Running job ${{ env.JOB_ID }} of ${{ env.WORKFLOW_NAME }} in step ${{ env.STEP_NAME }}"
              env: 
                STEP_NAME: workflowInfo


    

